# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/home/whatsis/Graphics/Assignment 2/20161073_Assignment2"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/home/whatsis/Graphics/Assignment 2/20161073_Assignment2"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/whatsis/Graphics/Assignment 2/20161073_Assignment2/CMakeFiles" "/home/whatsis/Graphics/Assignment 2/20161073_Assignment2/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/whatsis/Graphics/Assignment 2/20161073_Assignment2/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named graphics_assign1

# Build rule for target.
graphics_assign1: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 graphics_assign1
.PHONY : graphics_assign1

# fast build rule for target.
graphics_assign1/fast:
	$(MAKE) -f CMakeFiles/graphics_assign1.dir/build.make CMakeFiles/graphics_assign1.dir/build
.PHONY : graphics_assign1/fast

src/audio.o: src/audio.cpp.o

.PHONY : src/audio.o

# target to build an object file
src/audio.cpp.o:
	$(MAKE) -f CMakeFiles/graphics_assign1.dir/build.make CMakeFiles/graphics_assign1.dir/src/audio.cpp.o
.PHONY : src/audio.cpp.o

src/audio.i: src/audio.cpp.i

.PHONY : src/audio.i

# target to preprocess a source file
src/audio.cpp.i:
	$(MAKE) -f CMakeFiles/graphics_assign1.dir/build.make CMakeFiles/graphics_assign1.dir/src/audio.cpp.i
.PHONY : src/audio.cpp.i

src/audio.s: src/audio.cpp.s

.PHONY : src/audio.s

# target to generate assembly for a file
src/audio.cpp.s:
	$(MAKE) -f CMakeFiles/graphics_assign1.dir/build.make CMakeFiles/graphics_assign1.dir/src/audio.cpp.s
.PHONY : src/audio.cpp.s

src/barrel.o: src/barrel.cpp.o

.PHONY : src/barrel.o

# target to build an object file
src/barrel.cpp.o:
	$(MAKE) -f CMakeFiles/graphics_assign1.dir/build.make CMakeFiles/graphics_assign1.dir/src/barrel.cpp.o
.PHONY : src/barrel.cpp.o

src/barrel.i: src/barrel.cpp.i

.PHONY : src/barrel.i

# target to preprocess a source file
src/barrel.cpp.i:
	$(MAKE) -f CMakeFiles/graphics_assign1.dir/build.make CMakeFiles/graphics_assign1.dir/src/barrel.cpp.i
.PHONY : src/barrel.cpp.i

src/barrel.s: src/barrel.cpp.s

.PHONY : src/barrel.s

# target to generate assembly for a file
src/barrel.cpp.s:
	$(MAKE) -f CMakeFiles/graphics_assign1.dir/build.make CMakeFiles/graphics_assign1.dir/src/barrel.cpp.s
.PHONY : src/barrel.cpp.s

src/boat.o: src/boat.cpp.o

.PHONY : src/boat.o

# target to build an object file
src/boat.cpp.o:
	$(MAKE) -f CMakeFiles/graphics_assign1.dir/build.make CMakeFiles/graphics_assign1.dir/src/boat.cpp.o
.PHONY : src/boat.cpp.o

src/boat.i: src/boat.cpp.i

.PHONY : src/boat.i

# target to preprocess a source file
src/boat.cpp.i:
	$(MAKE) -f CMakeFiles/graphics_assign1.dir/build.make CMakeFiles/graphics_assign1.dir/src/boat.cpp.i
.PHONY : src/boat.cpp.i

src/boat.s: src/boat.cpp.s

.PHONY : src/boat.s

# target to generate assembly for a file
src/boat.cpp.s:
	$(MAKE) -f CMakeFiles/graphics_assign1.dir/build.make CMakeFiles/graphics_assign1.dir/src/boat.cpp.s
.PHONY : src/boat.cpp.s

src/boss.o: src/boss.cpp.o

.PHONY : src/boss.o

# target to build an object file
src/boss.cpp.o:
	$(MAKE) -f CMakeFiles/graphics_assign1.dir/build.make CMakeFiles/graphics_assign1.dir/src/boss.cpp.o
.PHONY : src/boss.cpp.o

src/boss.i: src/boss.cpp.i

.PHONY : src/boss.i

# target to preprocess a source file
src/boss.cpp.i:
	$(MAKE) -f CMakeFiles/graphics_assign1.dir/build.make CMakeFiles/graphics_assign1.dir/src/boss.cpp.i
.PHONY : src/boss.cpp.i

src/boss.s: src/boss.cpp.s

.PHONY : src/boss.s

# target to generate assembly for a file
src/boss.cpp.s:
	$(MAKE) -f CMakeFiles/graphics_assign1.dir/build.make CMakeFiles/graphics_assign1.dir/src/boss.cpp.s
.PHONY : src/boss.cpp.s

src/canon.o: src/canon.cpp.o

.PHONY : src/canon.o

# target to build an object file
src/canon.cpp.o:
	$(MAKE) -f CMakeFiles/graphics_assign1.dir/build.make CMakeFiles/graphics_assign1.dir/src/canon.cpp.o
.PHONY : src/canon.cpp.o

src/canon.i: src/canon.cpp.i

.PHONY : src/canon.i

# target to preprocess a source file
src/canon.cpp.i:
	$(MAKE) -f CMakeFiles/graphics_assign1.dir/build.make CMakeFiles/graphics_assign1.dir/src/canon.cpp.i
.PHONY : src/canon.cpp.i

src/canon.s: src/canon.cpp.s

.PHONY : src/canon.s

# target to generate assembly for a file
src/canon.cpp.s:
	$(MAKE) -f CMakeFiles/graphics_assign1.dir/build.make CMakeFiles/graphics_assign1.dir/src/canon.cpp.s
.PHONY : src/canon.cpp.s

src/color.o: src/color.cpp.o

.PHONY : src/color.o

# target to build an object file
src/color.cpp.o:
	$(MAKE) -f CMakeFiles/graphics_assign1.dir/build.make CMakeFiles/graphics_assign1.dir/src/color.cpp.o
.PHONY : src/color.cpp.o

src/color.i: src/color.cpp.i

.PHONY : src/color.i

# target to preprocess a source file
src/color.cpp.i:
	$(MAKE) -f CMakeFiles/graphics_assign1.dir/build.make CMakeFiles/graphics_assign1.dir/src/color.cpp.i
.PHONY : src/color.cpp.i

src/color.s: src/color.cpp.s

.PHONY : src/color.s

# target to generate assembly for a file
src/color.cpp.s:
	$(MAKE) -f CMakeFiles/graphics_assign1.dir/build.make CMakeFiles/graphics_assign1.dir/src/color.cpp.s
.PHONY : src/color.cpp.s

src/digit.o: src/digit.cpp.o

.PHONY : src/digit.o

# target to build an object file
src/digit.cpp.o:
	$(MAKE) -f CMakeFiles/graphics_assign1.dir/build.make CMakeFiles/graphics_assign1.dir/src/digit.cpp.o
.PHONY : src/digit.cpp.o

src/digit.i: src/digit.cpp.i

.PHONY : src/digit.i

# target to preprocess a source file
src/digit.cpp.i:
	$(MAKE) -f CMakeFiles/graphics_assign1.dir/build.make CMakeFiles/graphics_assign1.dir/src/digit.cpp.i
.PHONY : src/digit.cpp.i

src/digit.s: src/digit.cpp.s

.PHONY : src/digit.s

# target to generate assembly for a file
src/digit.cpp.s:
	$(MAKE) -f CMakeFiles/graphics_assign1.dir/build.make CMakeFiles/graphics_assign1.dir/src/digit.cpp.s
.PHONY : src/digit.cpp.s

src/gifts.o: src/gifts.cpp.o

.PHONY : src/gifts.o

# target to build an object file
src/gifts.cpp.o:
	$(MAKE) -f CMakeFiles/graphics_assign1.dir/build.make CMakeFiles/graphics_assign1.dir/src/gifts.cpp.o
.PHONY : src/gifts.cpp.o

src/gifts.i: src/gifts.cpp.i

.PHONY : src/gifts.i

# target to preprocess a source file
src/gifts.cpp.i:
	$(MAKE) -f CMakeFiles/graphics_assign1.dir/build.make CMakeFiles/graphics_assign1.dir/src/gifts.cpp.i
.PHONY : src/gifts.cpp.i

src/gifts.s: src/gifts.cpp.s

.PHONY : src/gifts.s

# target to generate assembly for a file
src/gifts.cpp.s:
	$(MAKE) -f CMakeFiles/graphics_assign1.dir/build.make CMakeFiles/graphics_assign1.dir/src/gifts.cpp.s
.PHONY : src/gifts.cpp.s

src/health.o: src/health.cpp.o

.PHONY : src/health.o

# target to build an object file
src/health.cpp.o:
	$(MAKE) -f CMakeFiles/graphics_assign1.dir/build.make CMakeFiles/graphics_assign1.dir/src/health.cpp.o
.PHONY : src/health.cpp.o

src/health.i: src/health.cpp.i

.PHONY : src/health.i

# target to preprocess a source file
src/health.cpp.i:
	$(MAKE) -f CMakeFiles/graphics_assign1.dir/build.make CMakeFiles/graphics_assign1.dir/src/health.cpp.i
.PHONY : src/health.cpp.i

src/health.s: src/health.cpp.s

.PHONY : src/health.s

# target to generate assembly for a file
src/health.cpp.s:
	$(MAKE) -f CMakeFiles/graphics_assign1.dir/build.make CMakeFiles/graphics_assign1.dir/src/health.cpp.s
.PHONY : src/health.cpp.s

src/input.o: src/input.cpp.o

.PHONY : src/input.o

# target to build an object file
src/input.cpp.o:
	$(MAKE) -f CMakeFiles/graphics_assign1.dir/build.make CMakeFiles/graphics_assign1.dir/src/input.cpp.o
.PHONY : src/input.cpp.o

src/input.i: src/input.cpp.i

.PHONY : src/input.i

# target to preprocess a source file
src/input.cpp.i:
	$(MAKE) -f CMakeFiles/graphics_assign1.dir/build.make CMakeFiles/graphics_assign1.dir/src/input.cpp.i
.PHONY : src/input.cpp.i

src/input.s: src/input.cpp.s

.PHONY : src/input.s

# target to generate assembly for a file
src/input.cpp.s:
	$(MAKE) -f CMakeFiles/graphics_assign1.dir/build.make CMakeFiles/graphics_assign1.dir/src/input.cpp.s
.PHONY : src/input.cpp.s

src/line.o: src/line.cpp.o

.PHONY : src/line.o

# target to build an object file
src/line.cpp.o:
	$(MAKE) -f CMakeFiles/graphics_assign1.dir/build.make CMakeFiles/graphics_assign1.dir/src/line.cpp.o
.PHONY : src/line.cpp.o

src/line.i: src/line.cpp.i

.PHONY : src/line.i

# target to preprocess a source file
src/line.cpp.i:
	$(MAKE) -f CMakeFiles/graphics_assign1.dir/build.make CMakeFiles/graphics_assign1.dir/src/line.cpp.i
.PHONY : src/line.cpp.i

src/line.s: src/line.cpp.s

.PHONY : src/line.s

# target to generate assembly for a file
src/line.cpp.s:
	$(MAKE) -f CMakeFiles/graphics_assign1.dir/build.make CMakeFiles/graphics_assign1.dir/src/line.cpp.s
.PHONY : src/line.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/graphics_assign1.dir/build.make CMakeFiles/graphics_assign1.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/graphics_assign1.dir/build.make CMakeFiles/graphics_assign1.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/graphics_assign1.dir/build.make CMakeFiles/graphics_assign1.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/monster.o: src/monster.cpp.o

.PHONY : src/monster.o

# target to build an object file
src/monster.cpp.o:
	$(MAKE) -f CMakeFiles/graphics_assign1.dir/build.make CMakeFiles/graphics_assign1.dir/src/monster.cpp.o
.PHONY : src/monster.cpp.o

src/monster.i: src/monster.cpp.i

.PHONY : src/monster.i

# target to preprocess a source file
src/monster.cpp.i:
	$(MAKE) -f CMakeFiles/graphics_assign1.dir/build.make CMakeFiles/graphics_assign1.dir/src/monster.cpp.i
.PHONY : src/monster.cpp.i

src/monster.s: src/monster.cpp.s

.PHONY : src/monster.s

# target to generate assembly for a file
src/monster.cpp.s:
	$(MAKE) -f CMakeFiles/graphics_assign1.dir/build.make CMakeFiles/graphics_assign1.dir/src/monster.cpp.s
.PHONY : src/monster.cpp.s

src/nonedit.o: src/nonedit.cpp.o

.PHONY : src/nonedit.o

# target to build an object file
src/nonedit.cpp.o:
	$(MAKE) -f CMakeFiles/graphics_assign1.dir/build.make CMakeFiles/graphics_assign1.dir/src/nonedit.cpp.o
.PHONY : src/nonedit.cpp.o

src/nonedit.i: src/nonedit.cpp.i

.PHONY : src/nonedit.i

# target to preprocess a source file
src/nonedit.cpp.i:
	$(MAKE) -f CMakeFiles/graphics_assign1.dir/build.make CMakeFiles/graphics_assign1.dir/src/nonedit.cpp.i
.PHONY : src/nonedit.cpp.i

src/nonedit.s: src/nonedit.cpp.s

.PHONY : src/nonedit.s

# target to generate assembly for a file
src/nonedit.cpp.s:
	$(MAKE) -f CMakeFiles/graphics_assign1.dir/build.make CMakeFiles/graphics_assign1.dir/src/nonedit.cpp.s
.PHONY : src/nonedit.cpp.s

src/other_handlers.o: src/other_handlers.cpp.o

.PHONY : src/other_handlers.o

# target to build an object file
src/other_handlers.cpp.o:
	$(MAKE) -f CMakeFiles/graphics_assign1.dir/build.make CMakeFiles/graphics_assign1.dir/src/other_handlers.cpp.o
.PHONY : src/other_handlers.cpp.o

src/other_handlers.i: src/other_handlers.cpp.i

.PHONY : src/other_handlers.i

# target to preprocess a source file
src/other_handlers.cpp.i:
	$(MAKE) -f CMakeFiles/graphics_assign1.dir/build.make CMakeFiles/graphics_assign1.dir/src/other_handlers.cpp.i
.PHONY : src/other_handlers.cpp.i

src/other_handlers.s: src/other_handlers.cpp.s

.PHONY : src/other_handlers.s

# target to generate assembly for a file
src/other_handlers.cpp.s:
	$(MAKE) -f CMakeFiles/graphics_assign1.dir/build.make CMakeFiles/graphics_assign1.dir/src/other_handlers.cpp.s
.PHONY : src/other_handlers.cpp.s

src/rocks.o: src/rocks.cpp.o

.PHONY : src/rocks.o

# target to build an object file
src/rocks.cpp.o:
	$(MAKE) -f CMakeFiles/graphics_assign1.dir/build.make CMakeFiles/graphics_assign1.dir/src/rocks.cpp.o
.PHONY : src/rocks.cpp.o

src/rocks.i: src/rocks.cpp.i

.PHONY : src/rocks.i

# target to preprocess a source file
src/rocks.cpp.i:
	$(MAKE) -f CMakeFiles/graphics_assign1.dir/build.make CMakeFiles/graphics_assign1.dir/src/rocks.cpp.i
.PHONY : src/rocks.cpp.i

src/rocks.s: src/rocks.cpp.s

.PHONY : src/rocks.s

# target to generate assembly for a file
src/rocks.cpp.s:
	$(MAKE) -f CMakeFiles/graphics_assign1.dir/build.make CMakeFiles/graphics_assign1.dir/src/rocks.cpp.s
.PHONY : src/rocks.cpp.s

src/score.o: src/score.cpp.o

.PHONY : src/score.o

# target to build an object file
src/score.cpp.o:
	$(MAKE) -f CMakeFiles/graphics_assign1.dir/build.make CMakeFiles/graphics_assign1.dir/src/score.cpp.o
.PHONY : src/score.cpp.o

src/score.i: src/score.cpp.i

.PHONY : src/score.i

# target to preprocess a source file
src/score.cpp.i:
	$(MAKE) -f CMakeFiles/graphics_assign1.dir/build.make CMakeFiles/graphics_assign1.dir/src/score.cpp.i
.PHONY : src/score.cpp.i

src/score.s: src/score.cpp.s

.PHONY : src/score.s

# target to generate assembly for a file
src/score.cpp.s:
	$(MAKE) -f CMakeFiles/graphics_assign1.dir/build.make CMakeFiles/graphics_assign1.dir/src/score.cpp.s
.PHONY : src/score.cpp.s

src/timer.o: src/timer.cpp.o

.PHONY : src/timer.o

# target to build an object file
src/timer.cpp.o:
	$(MAKE) -f CMakeFiles/graphics_assign1.dir/build.make CMakeFiles/graphics_assign1.dir/src/timer.cpp.o
.PHONY : src/timer.cpp.o

src/timer.i: src/timer.cpp.i

.PHONY : src/timer.i

# target to preprocess a source file
src/timer.cpp.i:
	$(MAKE) -f CMakeFiles/graphics_assign1.dir/build.make CMakeFiles/graphics_assign1.dir/src/timer.cpp.i
.PHONY : src/timer.cpp.i

src/timer.s: src/timer.cpp.s

.PHONY : src/timer.s

# target to generate assembly for a file
src/timer.cpp.s:
	$(MAKE) -f CMakeFiles/graphics_assign1.dir/build.make CMakeFiles/graphics_assign1.dir/src/timer.cpp.s
.PHONY : src/timer.cpp.s

src/water.o: src/water.cpp.o

.PHONY : src/water.o

# target to build an object file
src/water.cpp.o:
	$(MAKE) -f CMakeFiles/graphics_assign1.dir/build.make CMakeFiles/graphics_assign1.dir/src/water.cpp.o
.PHONY : src/water.cpp.o

src/water.i: src/water.cpp.i

.PHONY : src/water.i

# target to preprocess a source file
src/water.cpp.i:
	$(MAKE) -f CMakeFiles/graphics_assign1.dir/build.make CMakeFiles/graphics_assign1.dir/src/water.cpp.i
.PHONY : src/water.cpp.i

src/water.s: src/water.cpp.s

.PHONY : src/water.s

# target to generate assembly for a file
src/water.cpp.s:
	$(MAKE) -f CMakeFiles/graphics_assign1.dir/build.make CMakeFiles/graphics_assign1.dir/src/water.cpp.s
.PHONY : src/water.cpp.s

src/waves.o: src/waves.cpp.o

.PHONY : src/waves.o

# target to build an object file
src/waves.cpp.o:
	$(MAKE) -f CMakeFiles/graphics_assign1.dir/build.make CMakeFiles/graphics_assign1.dir/src/waves.cpp.o
.PHONY : src/waves.cpp.o

src/waves.i: src/waves.cpp.i

.PHONY : src/waves.i

# target to preprocess a source file
src/waves.cpp.i:
	$(MAKE) -f CMakeFiles/graphics_assign1.dir/build.make CMakeFiles/graphics_assign1.dir/src/waves.cpp.i
.PHONY : src/waves.cpp.i

src/waves.s: src/waves.cpp.s

.PHONY : src/waves.s

# target to generate assembly for a file
src/waves.cpp.s:
	$(MAKE) -f CMakeFiles/graphics_assign1.dir/build.make CMakeFiles/graphics_assign1.dir/src/waves.cpp.s
.PHONY : src/waves.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... graphics_assign1"
	@echo "... rebuild_cache"
	@echo "... src/audio.o"
	@echo "... src/audio.i"
	@echo "... src/audio.s"
	@echo "... src/barrel.o"
	@echo "... src/barrel.i"
	@echo "... src/barrel.s"
	@echo "... src/boat.o"
	@echo "... src/boat.i"
	@echo "... src/boat.s"
	@echo "... src/boss.o"
	@echo "... src/boss.i"
	@echo "... src/boss.s"
	@echo "... src/canon.o"
	@echo "... src/canon.i"
	@echo "... src/canon.s"
	@echo "... src/color.o"
	@echo "... src/color.i"
	@echo "... src/color.s"
	@echo "... src/digit.o"
	@echo "... src/digit.i"
	@echo "... src/digit.s"
	@echo "... src/gifts.o"
	@echo "... src/gifts.i"
	@echo "... src/gifts.s"
	@echo "... src/health.o"
	@echo "... src/health.i"
	@echo "... src/health.s"
	@echo "... src/input.o"
	@echo "... src/input.i"
	@echo "... src/input.s"
	@echo "... src/line.o"
	@echo "... src/line.i"
	@echo "... src/line.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/monster.o"
	@echo "... src/monster.i"
	@echo "... src/monster.s"
	@echo "... src/nonedit.o"
	@echo "... src/nonedit.i"
	@echo "... src/nonedit.s"
	@echo "... src/other_handlers.o"
	@echo "... src/other_handlers.i"
	@echo "... src/other_handlers.s"
	@echo "... src/rocks.o"
	@echo "... src/rocks.i"
	@echo "... src/rocks.s"
	@echo "... src/score.o"
	@echo "... src/score.i"
	@echo "... src/score.s"
	@echo "... src/timer.o"
	@echo "... src/timer.i"
	@echo "... src/timer.s"
	@echo "... src/water.o"
	@echo "... src/water.i"
	@echo "... src/water.s"
	@echo "... src/waves.o"
	@echo "... src/waves.i"
	@echo "... src/waves.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

